### ISSUE TITLE
CLIENT>CUSTOMER PERSONAL>CUSTOMER LIST

### ISSUE THREAD

**Issue by madjanuar** [MisterFix-System/AdminApp.Changelog#14]
WISH
Menampilkan
- Customer  ID
- Name
- Mobile Phone
- Alamat
- Total AC
- Action (View all ac recorded)

IMPLEMENTATION
Baru Menampilkan
- Name
- Phone
- Total AC
- Action

Screen Shoot Wish

**Comment by igrwijaya** [comment]
related with https://github.com/MisterFix-System/AdminApp.Changelog/issues/15

**Comment by igrwijaya** [comment]
saran: alamat ada kemungkinan karakternya akan cukup panjang, dan tentunya akan merusak tampilan tabel. Jadi lebih baik kolom alamat dimunculkan di detail customer

**Comment by madjanuar** [comment]
oke noted derah, 
issue closed, thanks
