### ISSUE TITLE
UTILITY>MAIN WEB CONTENT>MAIN WEB CONTENT LIST

### ISSUE THREAD

**Issue by madjanuar** [MisterFix-System/AdminApp.Changelog#42]
WISH
Menampilkan
- Tittle
- Page
- Section No
- Publish Status 

IMPLEMENTATION
Menampilkan
- Tittle
- Page
- Section No

**Comment by igrwijaya** [comment]
Publish status kurang sesuai diterapkan di fitur ini, kalau tidak dipublish bisa merusak tampilan desain di main web

**Comment by madjanuar** [comment]
Noted derah,

issue closed, thank you
