### ISSUE TITLE
UTILITY>MAIN WEB CONTENT> CREATE / UPDATE MAIN WEB CONTENT

### ISSUE THREAD

**Issue by madjanuar** [MisterFix-System/AdminApp.Changelog#43]
WISH 
Menampilkan
- Page
- Section
- Tittle
- Subtittle
- Descrisption (dengan text Editor)
- Image
- Publish Status

IMPLEMENTATION
menampilkan
- Page 
- Section
- Tittle
- Subttitle
- Description
- Image

**Comment by igrwijaya** [comment]
Publish status kurang sesuai diterapkan di fitur ini, kalau tidak dipublish bisa merusak tampilan desain di main web
