### ISSUE TITLE
ADMIN WEB>PRODUCT>PRODUCT ITEM>PRICE CONFIGURATION LIST

### ISSUE THREAD

**Issue by madjanuar** [MisterFix-System/AdminApp.Changelog#5]
WISH
Menampilkan
- Product ID
- Nama Item (Sub Product)
- Unit Info (Brand Spesifik/AC PK)
- Quantity
- Price 

IMPLEMENTATION
Baru menampilkan
- AC Info (Brand | PK)
- Unit Quantity
- Price

Screen Shoot Wish
![Price Configuration List ](https://user-images.githubusercontent.com/83683028/120739209-ba984280-c523-11eb-8526-e2e3aeab988e.png)

**Comment by igrwijaya** [comment]
Nama Item (Sub Product) -> sudah sempat kita diskusikan, price config hanya untuk mengatur harga, tidak ada nama produk tambahan di fitur ini.

**Comment by madjanuar** [comment]
Noted, issue Clossed, thank you
